# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4651eb2197722332b8d0cf52256322e620a2b2c8e656952ea9b9e0856bf6790e207c96b3ce970a0f5746209d88def7bbdab6df9f90ee974f4d7c261d78f147c

test:
  secret_key_base: f8e1ee45fc3887c70e1014b501b9222cdac2292b719f9b3b83b9da3808728a62fe5c608c5685de9fcabd20b0ef44b0fb6044aea4ec38a96b192e9cb0f92cb2a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
